# Generated by Django 3.1.2 on 2020-10-03 06:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Blocked user',
                'verbose_name_plural': 'Blocked users',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=10, verbose_name='Name ru')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Full name')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Phone number')),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
                ('related_people', models.TextField(null=True, verbose_name='Related people')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Is blocked')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customer.gender', verbose_name='Gender')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(null=True)),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('people_quantity', models.IntegerField(null=True, verbose_name='People quantity')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_requests', to='customer.customer', verbose_name='Customer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
