# Generated by Django 3.1.2 on 2020-10-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=2, null=True, verbose_name='Language'),
        ),
    ]
