# Generated by Django 3.1.2 on 2020-10-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookrequest',
            options={'ordering': ('-created_at',), 'verbose_name': 'Book request', 'verbose_name_plural': 'Book requests'},
        ),
    ]
