# Generated by Django 3.1.2 on 2020-10-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookrequest',
            options={'ordering': ('-confirmed_at',), 'verbose_name': 'Book request', 'verbose_name_plural': 'Book requests'},
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='date',
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='confirmed_at',
            field=models.DateTimeField(null=True, verbose_name='Confirmed at'),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='datetime',
            field=models.DateTimeField(null=True, verbose_name='Datetime'),
        ),
    ]
