# Generated by Django 3.1.2 on 2020-10-03 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20201003_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
    ]
