# Generated by Django 3.1.2 on 2021-03-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
    ]
