# Generated by Django 3.1.2 on 2021-03-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210312_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='notified_at',
            field=models.DateTimeField(null=True, verbose_name='Notified at'),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='feedback_requested_at',
            field=models.DateTimeField(null=True, verbose_name='Feedback requested at'),
        )
    ]
