# Generated by Django 3.1.2 on 2020-10-27 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20201024_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='gender',
            name='text',
            field=models.CharField(max_length=10, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='gender',
            name='text_en',
            field=models.CharField(max_length=10, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='gender',
            name='text_ru',
            field=models.CharField(max_length=10, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
    ]
