# Generated by Django 3.1.2 on 2020-10-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekday',
            name='name',
            field=models.CharField(max_length=2, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='name_en',
            field=models.CharField(max_length=2, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='name_ru',
            field=models.CharField(max_length=2, null=True, unique=True, verbose_name='Name'),
        ),
    ]
