# Generated by Django 3.1.2 on 2020-10-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatsManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_seats_number', models.PositiveIntegerField(default=50, verbose_name='Seats number')),
                ('additional_seats_number', models.PositiveIntegerField(default=0, verbose_name='Additional seats number')),
            ],
            options={
                'verbose_name': 'Seats manager',
                'verbose_name_plural': 'Seats manager',
            },
        ),
    ]
