# Generated by Django 3.1.2 on 2020-10-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_seatsmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tart_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
            ],
            options={
                'verbose_name': 'Working hours',
                'verbose_name_plural': 'Working hours',
            },
        ),
    ]
