# Generated by Django 3.1.2 on 2020-10-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_workinghours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinghours',
            old_name='tart_time',
            new_name='start_time',
        ),
    ]
