# Generated by Django 3.1.2 on 2020-10-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20201024_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=2, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=2, null=True, verbose_name='Name')),
            ],
        ),
    ]
