# Generated by Django 3.1.2 on 2020-10-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20201028_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekday',
            options={'ordering': ('id',), 'verbose_name': 'Weekday', 'verbose_name_plural': 'Weekdays'},
        ),
    ]
