# Generated by Django 3.1.2 on 2020-10-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='text_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='button',
            name='text_ru',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='message',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='text_ru',
            field=models.TextField(null=True),
        ),
    ]
